# syntax=docker/dockerfile:1.7
FROM docker.io/pytorch/pytorch:2.9.1-cuda12.8-cudnn9-devel

LABEL org.opencontainers.image.title="fetal-ultrasound-edm2" \
      org.opencontainers.image.description="Docker image for fetal-ultrasound-edm2" \
      org.opencontainers.image.authors="Miguel Xochicale" \
      org.opencontainers.image.url="https://github.com/xfetus/fetal-ultrasound-edm2/pkgs/container/fetal-ultrasound-edm2%2Ffetal-ultrasound-edm2-distributed-learning" \
      org.opencontainers.image.source="https://github.com/xfetus/fetal-ultrasound-edm2" \
      org.opencontainers.image.licenses="Apache-2.0"

RUN mkdir -p /workspace && chmod -R 777 /workspace
RUN mkdir -p /.cache/pip /.local && chmod -R 777 /.cache/pip /.local

WORKDIR /workspace
